var myFullName;
console.log(myFullName);
myFullName = "Sarthak Kadav";
console.log(myFullName);
myFullName = "Sarthak Ramdas Kadav";
console.log(myFullName);
var myLove="I love only Js";
console.log(myLove);
var firstName="Sarthak";
console.log(firstName);
var lastName ="Kadav";
console.log(lastName);
var age="23";
console.log(age);
var address = "Pune";
console.log(address);
var pinCode= "411017";
console.log(pinCode);
var gender = "Male";
console.log(gender);
var isMarried = "No";
console.log(isMarried);