console.log("===========Assingment No 2================");
console.log("--------Step 1-------------");
var bankName;
console.log("--------before initiallization-------------");
console.log(bankName,typeof bankName);
bankName="SBI Bank";
console.log("--------After initiallization-------------");
console.log(bankName, typeof bankName);
console.log("--------Step 2-------------");
var marks ='90%';
console.log(marks, typeof marks);
console.log("--------Step 3-------------");
var isWorking ;
console.log("--------before initiallization-------------");
console.log(isWorking,typeof isWorking);
isWorking = true;
console.log("--------After initiallization-------------");
console.log(isWorking,typeof isWorking);
console.log("--------Step 4-------------");
var totalCount="Hundread and Seven";
console.log(totalCount,typeof totalCount);
totalCount=107;
console.log(totalCount,typeof totalCount);